name: CI (Playwright Regression)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    # ✅ Use the official Playwright image with browsers & deps preinstalled
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy

    timeout-minutes: 30
    env:
      TARGET_URL: https://churchtalksrm.com

    steps:
      - uses: actions/checkout@v4

      # Node + npm are already in the container, just install deps
      - run: npm ci

      - name: Run regression tests
        run: npx playwright test -c playwright.regression.config.cjs

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
