name: CI (Playwright Regression)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-22.04        # pin to 22.04 to avoid apt issues
    timeout-minutes: 30
    env:
      TARGET_URL: https://churchtalksrm.com
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # ✅ New way: install browsers + required Linux deps
      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps chromium firefox webkit

      - name: Run regression tests
        run: npx playwright test -c playwright.regression.config.cjs

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
