name: CI (Playwright Regression)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest

    # ✅ Use official Playwright image and set HOME for the container process
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --user 0                   # run as root explicitly
      env:
        HOME: /root                       # <-- make HOME owned by root

    timeout-minutes: 30
    env:
      TARGET_URL: https://churchtalksrm.com
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

    steps:
      - uses: actions/checkout@v4

      - name: Show container user and HOME
        run: |
          whoami
          id -u
          echo "HOME=$HOME"
          ls -ld "$HOME"

      - run: npm ci

      - name: Verify Playwright in container
        run: npx playwright --version

      - name: Run regression tests
        run: npx playwright test -c playwright.regression.config.cjs

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
